# SITE CONFIGURATION
baseurl: "/helloeringirard.github.io" # te subpath of your site, e.g. /blog/
url: "http://eringirard.com" # te base hostname & protocol for your site

# THEME-SPECIFIC CONFIGURATION
theme:
  # Meta
  title: Erin Girard
  description: "Personal portfolio for a San Francisco UX and Visual Designer" # used by search engines

  # Header and footer text
  header_text: <p>""</p>
  header_text_feature_image: 
  footer_text: >
   Powered by <a href="http://jekyllrb.com">Jekyll</a> and made with love.

  # Icons
  rss: false
  email_address: helloeringirard@gmail.com
  behance:
  bitbucket:
  dribbble: 
  facebook: 
  flickr:
  github: 
  google_plus:
  instagram: helloerin
  linkedin:  https://www.linkedin.com/in/helloeringirard
  pinterest: OhHiErin
  reddit:
  soundcloud:
  stack_exchange:  # Full URL
  steam:
  tumblr:
  twitter: 
  wordpress:
  youtube:

  # Scripts
  google_analytics: "UA-75774807-1"
  disqus_shortname:
  katex: true # Enable if using math markup

  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_email: "Email"
  str_next: "Next"
  str_prev: "Prev"
  str_continue_reading: "Read more &raquo;"

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"
  google_fonts: "Libre Baskerville:400,700,400italic,700italic"

# PAGINATION
paginate: 100
paginate_path: "blog/page:num"

# COLLECTIONS
collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/

# BUILD SETTINGS
markdown: kramdown

highlighter: pygments
sass:
  sass_dir: _sass
  style: :compressed

gems: [jekyll-paginate]
